### ISSUE TITLE
dashing-icinga2 wont start

### ISSUE THREAD

**Issue by curantes** [mocdaniel/dashing-icinga2#10]
I followed the instructions for installation, setup and configuration according to README.md and after running `./restart-dashing` I get the following errors.

The server is a CentOS 7

```
Unable to load the EventMachine C extension; To use the pure-ruby reactor, require 'em/pure_ruby'
bundler: failed to load command: thin (/usr/local/bin/thin)
LoadError: cannot load such file -- rubyeventmachine
  /usr/local/share/gems/gems/eventmachine-1.2.2/lib/eventmachine.rb:8:in `require'
  /usr/local/share/gems/gems/eventmachine-1.2.2/lib/eventmachine.rb:8:in `<top (required)>'
  /usr/local/share/gems/gems/thin-1.6.4/lib/thin.rb:7:in `require'
  /usr/local/share/gems/gems/thin-1.6.4/lib/thin.rb:7:in `<top (required)>'
  /usr/local/share/gems/gems/thin-1.6.4/bin/thin:5:in `require'
  /usr/local/share/gems/gems/thin-1.6.4/bin/thin:5:in `<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in `<top (required)>
```

**Comment by mddeff** [comment]
I'm seeing the same problem, also on CentOS 7.2.11.

**Comment by dnsmichi** [comment]
Run dashing in foreground and verify that all dependencies are installed. Your error looks like you did not successfully run `bundle install` and thus the eventmachine support is not compiled.

**Comment by mddeff** [comment]
I think everything got installed correctly.  Re-running `bundle install --system` seems to go smoothly.

### Original output of `bundle install --system`
```
[root@monsvr dashing-icinga2]# bundle install --system
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Rubygems 2.0.14 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using backports 3.6.8
Using coffee-script-source 1.12.2
Using execjs 2.0.2
Using daemons 1.2.4
Using rack 1.5.5
Using thread_safe 0.3.5
Using sass 3.2.19
Using tilt 1.4.1
Using multi_json 1.12.1
Using hike 1.2.3
Using eventmachine 1.2.2
Installing thor 0.19.4
Installing unf_ext 0.0.7.2 with native extensions
Installing json 2.0.3 with native extensions
Installing mime-types-data 3.2016.0521
Installing netrc 0.11.0
Using bundler 1.14.3
Using coffee-script 2.2.0
Using rack-protection 1.5.3
Using rack-test 0.6.3
Using tzinfo 1.2.2
Using sprockets 2.10.2
Using thin 1.6.4
Installing unf 0.1.4
Installing mime-types 3.1
Using sinatra 1.4.8
Using rufus-scheduler 2.0.24
Installing domain_name 0.5.20161129
Using sinatra-contrib 1.4.7
Installing http-cookie 1.0.3
Using dashing 1.3.7
Installing rest-client 2.0.0
Bundle complete! 5 Gemfile dependencies, 32 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

### Output of re-running `bundle install --system`
```
[root@monsvr dashing-icinga2]# bundle install --system
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Rubygems 2.0.14 is not threadsafe, so your gems will be installed one at a time. Upgrade to Rubygems 2.1.0 or higher to enable parallel gem installation.
Using backports 3.6.8
Using coffee-script-source 1.12.2
Using execjs 2.0.2
Using daemons 1.2.4
Using rack 1.5.5
Using thread_safe 0.3.5
Using sass 3.2.19
Using tilt 1.4.1
Using multi_json 1.12.1
Using hike 1.2.3
Using eventmachine 1.2.2
Using thor 0.19.4
Using unf_ext 0.0.7.2
Using json 2.0.3
Using mime-types-data 3.2016.0521
Using netrc 0.11.0
Using bundler 1.14.3
Using coffee-script 2.2.0
Using rack-protection 1.5.3
Using rack-test 0.6.3
Using tzinfo 1.2.2
Using sprockets 2.10.2
Using thin 1.6.4
Using unf 0.1.4
Using mime-types 3.1
Using sinatra 1.4.8
Using rufus-scheduler 2.0.24
Using domain_name 0.5.20161129
Using sinatra-contrib 1.4.7
Using http-cookie 1.0.3
Using dashing 1.3.7
Using rest-client 2.0.0
Bundle complete! 5 Gemfile dependencies, 32 gems now installed.
Use bundle show `[gemname]` to see where a bundled gem is installed.
```

Still getting the same error as @curantes

**Comment by nioupola** [comment]
Hi all :)

I have the same issue but I solved it by using : ```bundle install --path binpaths``` instead of ```bundle install --system```.

I hope can help you to solve it too.

edit : I make a PR for add this to the readme : https://github.com/Icinga/dashing-icinga2/pull/11

**Comment by Copis** [comment]
Maybe will be better to specify that's command need to be runed into "/usr/share/dashing-icinga2"
I followed this guide to make it work on Centos. 
http://brunner-it.de/2016/08/04/icinga2-dashing-installieren/

**Comment by nioupola** [comment]
Thanks for the tip. I edit again the README to add the ```cd``` command 👍

**Comment by dnsmichi** [comment]
Hm, when installing it locally you won't have the dashing gem pulled into /usr/local/bin. 

I've re-evaluated the docs based on Docker containers with Centos7 and Debian8. Both work when installing the gems using `bundle`.

I'll push a documentation patch soon.

**Comment by BeneCzech** [comment]
# ## ### 

> [`_****_`](

- url

)
