### ISSUE TITLE
[Bug] DOWN Hosts are not displayed correctly and throw errors: "no implicit conversion of nil into string"

### ISSUE THREAD

**Issue by mocdaniel** [mocdaniel/dashing-icinga2#120]
While querying for information, dashing-icinga2 seems to mess up if hosts are down - not a very helpful feature. All other information regarding other hosts and their possibly faulty services still work:

```
================================================================================
scheduler caught exception:
no implicit conversion of nil into String
/usr/share/dashing-icinga2/lib/icinga2.rb:634:in `+'
/usr/share/dashing-icinga2/lib/icinga2.rb:634:in `block in getProblemServices'
/usr/share/dashing-icinga2/lib/icinga2.rb:620:in `each'
/usr/share/dashing-icinga2/lib/icinga2.rb:620:in `getProblemServices'
/usr/share/dashing-icinga2/lib/icinga2.rb:838:in `run'
/usr/share/dashing-icinga2/jobs/icinga2.rb:27:in `block in <top (required)>'
/var/lib/gems/2.5.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/2.5.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/2.5.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
```

First reported in #119

**Comment by mocdaniel** [comment]
Fixed.

**Comment by elguenny** [comment]
I can confirm this. Thx a lot
![Dashboard-Icinga 2](https://user-images.githubusercontent.com/1764902/124266894-d9482400-db37-11eb-9a2d-361d8043da30.png)
